<?php

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\Attributes\UsesClass;
use PHPUnit\Framework\Attributes\CoversClass;

use Gbhorwood\Tabletown\Table;

/**
 * ArraysAlignmentTest
 *
 * Test column alignment parameters
 */

#[CoversClass(\Gbhorwood\Tabletown\Table::class)]
#[UsesClass(\Gbhorwood\Tabletown\Table::class)]
class ArraysAlignmentTest extends TestCase
{
    /**
     * Test get($headers, $data, $border, $alignment) alignments with standard border
     *
     * @dataProvider arraysProviderStandardBorderAlignment
     */
    public function testArraysTableStandardBorderAlignment($headers, $data, $alignment, $expected)
    {
        $result = Table::get($headers, $data, null, $alignment);
        $this->assertEquals($result, $expected);
    }

    /**
     * Provider for header and data arrays with expected output
     * standard border
     */
    public static function arraysProviderStandardBorderAlignment(): array
    {
        return [
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [0,0,0], "+------------------+----------------+-----------------+".PHP_EOL."| art     ist🚀    | ti🚀tle        | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."| Bratmobile       | Pott    ymouth | 1993            |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  | 1959            |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [1,0,0], "+------------------+----------------+-----------------+".PHP_EOL."|  art     ist🚀   | ti🚀tle        | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|    Bratmobile    | Pott    ymouth | 1993            |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  | 1959            |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [0,1,0], "+------------------+----------------+-----------------+".PHP_EOL."| art     ist🚀    |    ti🚀tle     | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."| Bratmobile       | Pott    ymouth | 1993            |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  | 1959            |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [0,0,1], "+------------------+----------------+-----------------+".PHP_EOL."| art     ist🚀    | ti🚀tle        | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."| Bratmobile       | Pott    ymouth |      1993       |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  |      1959       |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [1,1,1], "+------------------+----------------+-----------------+".PHP_EOL."|  art     ist🚀   |    ti🚀tle     | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|    Bratmobile    | Pott    ymouth |      1993       |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  |      1959       |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [0,1,1], "+------------------+----------------+-----------------+".PHP_EOL."| art     ist🚀    |    ti🚀tle     | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."| Bratmobile       | Pott    ymouth |      1993       |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  |      1959       |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [1,0,1], "+------------------+----------------+-----------------+".PHP_EOL."|  art     ist🚀   | ti🚀tle        | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|    Bratmobile    | Pott    ymouth |      1993       |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  |      1959       |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [1,0,0], "+------------------+----------------+-----------------+".PHP_EOL."|  art     ist🚀   | ti🚀tle        | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|    Bratmobile    | Pott    ymouth | 1993            |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  | 1959            |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [1,1,0], "+------------------+----------------+-----------------+".PHP_EOL."|  art     ist🚀   |    ti🚀tle     | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|    Bratmobile    | Pott    ymouth | 1993            |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  | 1959            |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [0,0,0], "+------------------+----------------+-----------------+".PHP_EOL."| art     ist🚀    | ti🚀tle        | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."| Bratmobile       | Pott    ymouth | 1993            |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  | 1959            |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [2,0,0], "+------------------+----------------+-----------------+".PHP_EOL."|    art     ist🚀 | ti🚀tle        | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|       Bratmobile | Pott    ymouth | 1993            |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  | 1959            |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [0,2,0], "+------------------+----------------+-----------------+".PHP_EOL."| art     ist🚀    |        ti🚀tle | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."| Bratmobile       | Pott    ymouth | 1993            |".PHP_EOL."| Colt🚀rane, John |  Giant   Steps | 1959            |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [0,0,2], "+------------------+----------------+-----------------+".PHP_EOL."| art     ist🚀    | ti🚀tle        | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."| Bratmobile       | Pott    ymouth |            1993 |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  |            1959 |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [2,2,2], "+------------------+----------------+-----------------+".PHP_EOL."|    art     ist🚀 |        ti🚀tle | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|       Bratmobile | Pott    ymouth |            1993 |".PHP_EOL."| Colt🚀rane, John |  Giant   Steps |            1959 |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [0,2,2], "+------------------+----------------+-----------------+".PHP_EOL."| art     ist🚀    |        ti🚀tle | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."| Bratmobile       | Pott    ymouth |            1993 |".PHP_EOL."| Colt🚀rane, John |  Giant   Steps |            1959 |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [2,0,2], "+------------------+----------------+-----------------+".PHP_EOL."|    art     ist🚀 | ti🚀tle        | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|       Bratmobile | Pott    ymouth |            1993 |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  |            1959 |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [2,0,0], "+------------------+----------------+-----------------+".PHP_EOL."|    art     ist🚀 | ti🚀tle        | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|       Bratmobile | Pott    ymouth | 1993            |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  | 1959            |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [2,2,0], "+------------------+----------------+-----------------+".PHP_EOL."|    art     ist🚀 |        ti🚀tle | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|       Bratmobile | Pott    ymouth | 1993            |".PHP_EOL."| Colt🚀rane, John |  Giant   Steps | 1959            |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [2,2,2], "+------------------+----------------+-----------------+".PHP_EOL."|    art     ist🚀 |        ti🚀tle | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|       Bratmobile | Pott    ymouth |            1993 |".PHP_EOL."| Colt🚀rane, John |  Giant   Steps |            1959 |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [1,2,2], "+------------------+----------------+-----------------+".PHP_EOL."|  art     ist🚀   |        ti🚀tle | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|    Bratmobile    | Pott    ymouth |            1993 |".PHP_EOL."| Colt🚀rane, John |  Giant   Steps |            1959 |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [2,1,2], "+------------------+----------------+-----------------+".PHP_EOL."|    art     ist🚀 |    ti🚀tle     | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|       Bratmobile | Pott    ymouth |            1993 |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  |            1959 |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [2,2,1], "+------------------+----------------+-----------------+".PHP_EOL."|    art     ist🚀 |        ti🚀tle | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|       Bratmobile | Pott    ymouth |      1993       |".PHP_EOL."| Colt🚀rane, John |  Giant   Steps |      1959       |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [1,1,1], "+------------------+----------------+-----------------+".PHP_EOL."|  art     ist🚀   |    ti🚀tle     | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|    Bratmobile    | Pott    ymouth |      1993       |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  |      1959       |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [2,1,1], "+------------------+----------------+-----------------+".PHP_EOL."|    art     ist🚀 |    ti🚀tle     | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|       Bratmobile | Pott    ymouth |      1993       |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  |      1959       |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [1,2,1], "+------------------+----------------+-----------------+".PHP_EOL."|  art     ist🚀   |        ti🚀tle | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|    Bratmobile    | Pott    ymouth |      1993       |".PHP_EOL."| Colt🚀rane, John |  Giant   Steps |      1959       |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [1,2,2], "+------------------+----------------+-----------------+".PHP_EOL."|  art     ist🚀   |        ti🚀tle | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|    Bratmobile    | Pott    ymouth |            1993 |".PHP_EOL."| Colt🚀rane, John |  Giant   Steps |            1959 |".PHP_EOL."+------------------+----------------+-----------------+"],
            [["art	ist🚀","ti🚀tle","date but longer"], [["Bratmobile","Pott	ymouth","1993"],["Colt🚀rane, John","Giant	Steps","1959"]], [1,1,2], "+------------------+----------------+-----------------+".PHP_EOL."|  art     ist🚀   |    ti🚀tle     | date but longer |".PHP_EOL."+------------------+----------------+-----------------+".PHP_EOL."|    Bratmobile    | Pott    ymouth |            1993 |".PHP_EOL."| Colt🚀rane, John | Giant   Steps  |            1959 |".PHP_EOL."+------------------+----------------+-----------------+"],
        ];
    }
}
